### ISSUE TITLE
Updates: Gourse qPCR data format

### ISSUE THREAD

**Issue by nataliarosario2** [eburgoswisc/meltingShiftPy#1]
Two setups:

1.  triplicates: average every 3 rows
2. 3 separate experiments: average 3 separate sheets.

![Figure 1.](https://user-images.githubusercontent.com/43008341/56443235-5f5e5400-62b9-11e9-8383-b5ea1949bf70.JPG)

**Comment by eburgoswisc** [comment]
#2 Fixed with this pull request
